version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  __HOMEPAGE_DOCKER_TAG__:
    image: 102421067040.dkr.ecr.eu-central-1.amazonaws.com/coding-tree-homepage:__HOMEPAGE_DOCKER_TAG__
    networks:
      - web
    labels:
      - traefik.backend=coding-tree-homepage-__HOMEPAGE_TREAFIK_NAME__
      - traefik.frontend.rule=HostRegexp:__HOMEPAGE_URL__
      - traefik.docker.network=web
      - traefik.port=80
