version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:

  __BRANCH_NAME__:
    image: 102421067040.dkr.ecr.eu-central-1.amazonaws.com/coding-tree-homepage:__BRANCH_NAME__
    networks:
      - web
    labels:
      - traefik.backend=coding-tree-homepage-__BRANCH_NAME__
      - traefik.frontend.rule=HostRegexp:__BRANCH_NAME__.hp.codingtree.pl
      - traefik.docker.network=web
      - traefik.port=80
