export const lightTheme = {
  '--main-color': '#7f2538',
  '--background-color': '#ffffff88',
  '--breadcrump-color': '#f1f3f4aa',
  '--selected-color': '#fff',
  '--font-color': '#000',
  '--main-font-color': '#330b15',
  '--border-color': '#000',
  '--folder-color': '#df8230',
  '--text-color': '#000',
  '--white-color': '#fff',
  '--social-bg-color': '#7f2538',
  '--box-font': 'Nunito Sans',
  '--tree-color': '#4B101F',
  '--grass-color': '#330B15',
  '--ground-color': '#330B15',
  '--menu-color': '#e84855',
  '--modal-header-color': '#f1f3f4',
  '--modal-color': '#fff',
  '--border-color-box': '#f1f3f4',
  '--success-color': '#6bba62',
};

export const darkTheme = {
  '--main-color': '#fff',
  '--background-color': '#5E5E5F99',
  '--breadcrump-color': '#4B4B4B',
  '--selected-color': '#000',
  '--font-color': '#e3dede',
  '--main-font-color': '#e3dede',
  '--border-color': '#fff',
  '--folder-color': '#fff1b9',
  '--text-color': '#e3dede',
  '--white-color': '#fff',
  '--social-bg-color': '#5E5E5F',
  '--box-font': 'Nunito Sans',
  '--tree-color': '#323333',
  '--grass-color': '#3f4040',
  '--ground-color': '#272625',
  '--menu-color': '#fff1b9',
  '--modal-header-color': '#272625',
  '--modal-color': '#3f4040',
  '--border-color-box': '#272625',
  '--success-color': '#64a36f',
};
